#!/usr/bin/env perl
use warnings;
use strict;
use utf8;
use JSON;
use Smart::Comments;
binmode(STDIN, ":encoding(utf8)");
binmode(STDOUT, ":encoding(utf8)");

$| = 1;

# return codes
our ($state_ok,$state_warn,$state_crit,$state_unkn,$state_noop) = (0,1,2,3,4);

# return stuff
our ($rc, $result) = (0,'');

our $filename = (split /\//, __FILE__)[-1];

#
#  BEGIN to COLLECT SYSTEM INFORMATION 
#
my %load_avg = (
  '1min'	=> '',
  '5min'	=> '',
  '15min'	=> '',
);

my %cpu_usage = (
  'time'	=> '',
  'interval'	=> '',
  'user'	=> '',
  'sys'		=> '',
  'wait'	=> '',
  'idle'	=> '',
);

my @online_user = ();

my %runtime = (
  'boottime'	=> '',
  'runtime'	=> '',
  'idletime'	=> '',
);

my %mem_usage = (
  'mem_usage'	=> '',
  'swp_usage'	=> '',
);

my @prt_usage = ();

my %process = (
  'total_num'	=> '',
  'state_R'	=> '', 
  'stare_S'	=> '',
  'state_Z'	=> '',
  'state_D'	=> '',
);

my %netstat = (
  'total_num'	=> '',
);

my %lastlogin = (
  'number'	=> '',
  'result'	=> '',
);

# PREPARE LAST RESULT HASH
my %result = (
  'load_avg'	=> \%load_avg,
  'cpu_usage'	=> \%cpu_usage,
  'online_user'	=> \@online_user,
  'runtime'	=> \%runtime,
  'mem_usage'	=> \%mem_usage,
  'prt_usage'	=> \@prt_usage,
  'process'	=> \%process,
  'netstat'	=> \%netstat,
  'lastlogin'	=> \%lastlogin,
);
### %result

$result = JSON->new->utf8(1)->ascii(1)->encode(\%result);
print "{ok}:{str}:{$filename|$filename|$result}";
exit $state_ok;
