#!/usr/bin/env bash

# BASE_DIR DEF
[ -z ${BASE_DIR} ] && { 
        path=$( cd $(dirname $0) && pwd)
        BASE_DIR=${path%/*}
}

# === LOAD GETTEXT.SH FILE
if [ -f "/usr/bin/gettext.sh"  -a -s "/usr/bin/gettext.sh" ]; then
        source "/usr/bin/gettext.sh" 2>&1
        rc=$?
        [ "$rc" != "0" ] && {
                echo -en "{unkn}:{str}:{load [/usr/bin/gettext.sh] failed with status $rc}"
                exit 3
        }   
else
        echo -en "{unkn}:{str}:{[/usr/bin/gettext.sh] not exists or empty, maybe gettext not installed. exit}"
        exit 3
fi

# === LOAD INCLUDE FILE
if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
        source ${BASE_DIR}/bin/include 2>&- 
else    
        echo -en "{unkn}:{str}:{include file not exists or empty}"
        exit 3
fi

# === SET TEXTDOMAINDIR TEXTDOMAIN
if [ -d "${LOCALE_DIR}" -a -r "${LOCALE_DIR}" ]; then
        export TEXTDOMAINDIR="${LOCALE_DIR}"
        export TEXTDOMAIN="dns_svr"
else    
        echo -en "{unkn}:{str}:{locale directory [${LOCALE_DIR}] not exist or accessable, exit}"
        exit 3
fi


# === SET GLOBAL LOCALE
glocale=$(get_locale dns_svr)
if [ -z "${glocale}" ]; then
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
elif [ "${glocale}" == "zh_CN" -o "${glocale}" == "zh_CN.UTF-8" -o "${glocale}" == "zh" ]; then
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
elif [ "${glocale}" == "en_US" -o "${glocale}" == "en_US.UTF-8" -o "${glocale}" == "en" ]; then
        export LANG="en_US.UTF-8"  LC_ALL="en_US.UTF-8"
else
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
fi


show_help(){
cat <<EOF
Arguments:   {d|data|h|help} {dns_check_lst} {max_wait_time}

Usage:	 data  "eyou.net:mx,ns,soa  mail.eyou.net:a"  10

Output:   
Example:
EOF
exit 0;
}
MODE=0
[ "$1" == "data" -o "$1" == "d" ] && MODE=1
[ "$1" == "help" -o "$1" == "h" ] && show_help;


# Return Codes
STATE_SUCC=0
STATE_WARN=1
STATE_CRIT=2
STATE_UNKN=3
STATE_NOOP=4
STATE_NOTIFY=5

# Set Default
EXIT_STATUS=0
LEVEL=    	### { succ | warn | crit | unkn | noop | notify }
TYPE=   	### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
if [ "${MODE}" == "1" ]; then
	dns_check_lst="$2"
	max_wait_time="$3"
else
	dns_check_lst=$( read_mole_config dns_svr dns_check_lst )
	max_wait_time=$( read_mole_config dns_svr max_wait_time )
fi

# if null return STATE_UNKN.

# if null or invalid set default.
[ -z "${dns_check_lst}" ] && dns_check_lst="eyou.net:mx,ns"

# check function here
check(){

  [ -f "/usr/bin/host" -a -x "/usr/bin/host" ] || {
	EXIT_STATUS=${STATE_UNKN};
	LEVEL="unkn";
	TYPE="str";
	CONTENT="$(gettext "Util: [/usr/bin/host] not prepared.")"
	return
  }

  if is_int "${max_wait_time}"; then
        :
  else
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(eval_gettext "max_wait_time [\${max_wait_time}] should be int.")";
        return
  fi


  local result= warnnum=0  unknnum=0 total=0

  result="$(eval_gettext "DNS Check List: [\${dns_check_lst}]") ### ###"
  for x in `echo "${dns_check_lst}"`
  do
	target=$(echo -e "${x}" | awk -F: '{print $1}')
	types=$(echo -e "${x}" | awk -F: '{print $2}')
	for y in `echo -e "${types}" | tr '[,]' ' '`
	do
		((total++))
		error=$(/usr/bin/host -v -W ${max_wait_time} -t ${y} ${target} 2>&1)
		rc=$?
		y=$(echo -e "${y}" | tr '[a-z]' '[A-Z]')
		status=$(echo -e "${error}" |grep -E -o "status: (\w)+," | tail -n1)
		status=$(echo -e "${status}" | sed -e 's/status://g')
		if [ "${rc}" == "0" ]; then
			detail=$(echo -e "${error}" | awk '(/^Received/) {print}'  | tail -n1)
			result="${result} $(eval_gettext "dns resolving [\${y}] on [\${target}] succeed! details: \${status} \${detail}") ### "
		else
			((warnnum++))
			error=$(echo -e "${error}" | tr '\r\n' ' ')
			result="${result} $(html_red "$(eval_gettext "dns resolving [\${y}] on [\${target}] error! details: \${status} [\${error}]")") ### "
		fi
	done
	result="${result} ### "
  done

  # exit if MODE=1
  [ "${MODE}" == "1" ] && exit;

  [ "${warnnum}" -gt "0" ] && {
	EXIT_STATUS=${STATE_WARN};
	LEVEL="warn";
	TYPE="str";
	CONTENT="$(gettext "DNS SVR Check WARNING") | $(eval_gettext "\${warnnum}/\${total} check failed") | ${result} "
  } || {
	EXIT_STATUS="${STATE_SUCC}"
	LEVEL="succ"
	TYPE="str"
	CONTENT="$(gettext "DNS SVR Check OK") | $(eval_gettext "\${total}/\${total} check success") | ${result} "
  }
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
