#!/bin/bash

basedir="$(cd $(dirname $0);pwd)"
destdir="/data/esop_codes"
autorpm="${basedir}/rpm_build/autorpm"

check_rc() {
  if [ $? == 0 ]; then
        echo -e " -- $(date +%F_%T)  succed!  ${*}"
  else
        echo -e " -- $(date +%F_%T)  failed!  ${*}"; exit 1
  fi
}

# check root privilege
if [ "$(id -u)" != "0" ]; then
  echo " root privileges required! "
  exit 1
fi

# def spec files
spec_dir="$basedir/rpm_build/spec_files/"
spec_files=(
	# {xyz}.spec files for rpm ball {xyz}
	"esop-plugingroup-mail.spec"
)

# publish single spec files
for((i=0;i<=${#spec_files[*]}-1;i++))
do
	if [ -f "${spec_dir}/${spec_files[$i]}" ]; then
		/bin/cp  -f "${spec_dir}/${spec_files[$i]}"  "${destdir}/${spec_files[$i]}"
		check_rc "publish ${spec_files[$i]}"
	fi
done

# publish basic tarball
filename1=$( eval "${autorpm} basic tarball" )
check_rc "make tarball: $filename1"

ls "${filename1}" >/dev/null 2>&1
check_rc "check path: ${filename1}"

/bin/cp -f "${filename1}" "${destdir}/"
check_rc "copy to ${destdir}/${filename1##*/}"

# publish plugins-mailgroup tarball
filename2=$( eval "${autorpm} mail  tarball" )
check_rc "make tarball: $filename2"

ls "${filename2}" >/dev/null 2>&1
check_rc "check path: ${filename2}"

/bin/cp -f "${filename2}" "${destdir}/"
check_rc "copy to ${destdir}/${filename2##*/}"

# cleaning job
${autorpm} clean
check_rc "do cleaning"
