#!/usr/bin/env bash


# BASE_DIR DEF
[ -z ${BASE_DIR} ] && { 
        path=$( cd $(dirname $0) && pwd)
        BASE_DIR=${path%/*}
}

# === LOAD GETTEXT.SH FILE
if [ -f "/usr/bin/gettext.sh"  -a -s "/usr/bin/gettext.sh" ]; then
        source "/usr/bin/gettext.sh" 2>&1
        rc=$?
        [ "$rc" != "0" ] && {
                echo -en "{unkn}:{str}:{load [/usr/bin/gettext.sh] failed with status $rc}"
                exit 3
        }   
else
        echo -en "{unkn}:{str}:{[/usr/bin/gettext.sh] not exists or empty, maybe gettext not installed. exit}"
        exit 3
fi

# === LOAD INCLUDE FILE
if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
        source ${BASE_DIR}/bin/include 2>&- 
else    
        echo -en "{unkn}:{str}:{include file not exists or empty}"
        exit 3
fi

# === SET TEXTDOMAINDIR TEXTDOMAIN
if [ -d "${LOCALE_DIR}" -a -r "${LOCALE_DIR}" ]; then
        export TEXTDOMAINDIR="${LOCALE_DIR}"
        export TEXTDOMAIN="memory"
else    
        echo -en "{unkn}:{str}:{locale directory [${LOCALE_DIR}] not exist or accessable, exit}"
        exit 3
fi


# === SET GLOBAL LOCALE
glocale=$(get_locale memory)
if [ -z "${glocale}" ]; then
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
elif [ "${glocale}" == "zh_CN" -o "${glocale}" == "zh_CN.UTF-8" -o "${glocale}" == "zh" ]; then
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
elif [ "${glocale}" == "en_US" -o "${glocale}" == "en_US.UTF-8" -o "${glocale}" == "en" ]; then
        export LANG="en_US.UTF-8"  LC_ALL="en_US.UTF-8"
else
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
fi


show_help(){
cat <<EOF
Arguments:   {d|data|h|help}
Usage	 :   data
Output   :   {mem_size}M {mem_free}M {mem_used_pct}%  {swp_size}M {swp_free}M {swp_used_pct}%
Example  :   386M 313M 19.100%  799M 792M 1.000%
EOF
exit 0;
}
MODE=0
[ "$1" == "data" -o "$1" == "d" ] && MODE=1
[ "$1" == "help" -o "$1" == "h" ] && show_help;


# Return Codes
STATE_SUCC=0
STATE_WARN=1
STATE_CRIT=2
STATE_UNKN=3
STATE_NOOP=4
STATE_NOTIFY=5

# Set Default
EXIT_STATUS=0
LEVEL=    	### { succ | warn | crit | unkn | noop | notify }
TYPE=    	### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
mem_uplimit=$(read_mole_config memory mem_uplimit)
swp_uplimit=$(read_mole_config memory swp_uplimit)

# if null return STATE_UNKN.

# if null or invalid set default.

# check function here
check(){

  [ -f "/proc/meminfo" -a -r "/proc/meminfo" ] || {
	EXIT_STATUS=${STATE_UNKN};
	LEVEL="unkn";
	TYPE="str";
	CONTENT="$(gettext "File: [/proc/meminfo] not prepared.")";
	return
  }

  if is_float "${mem_uplimit}" || is_int "${mem_uplimit}" ; then
	:
  else
	EXIT_STATUS=${STATE_UNKN};
	LEVEL="unkn";
	TYPE="str";
	CONTENT="$(eval_gettext "mem_uplimit [\${mem_uplimit}] should be int or float.")";
	return
  fi

  if is_float "${swp_uplimit}" || is_int "${swp_uplimit}" ; then
	:
  else
	EXIT_STATUS=${STATE_UNKN};
	LEVEL="unkn";
	TYPE="str";
	CONTENT="$(eval_gettext "swp_uplimit [\${swp_uplimit}] should be int or float.")";
	return
  fi

  # collect data
  local mem_total=$(awk '/^MemTotal:/ {print $2;exit;}' /proc/meminfo 2>&-)
  local mem_free=$(awk '/^MemFree:/ {print $2;exit;}' /proc/meminfo 2>&-)
  local swp_total=$(awk '/^SwapTotal:/ {print $2;exit;}' /proc/meminfo 2>&-)
  local swp_free=$(awk '/^SwapFree:/ {print $2;exit;}' /proc/meminfo 2>&-)
  local mem_percent=$( echo "scale=3; 100 * (1 - ${mem_free}/${mem_total})" | bc 2>&- )
  local swp_percent=$( echo "scale=3; 100 * (1 - ${swp_free}/${swp_total})" | bc 2>&- )

  # human readable
  if (echo -e "${mem_percent}" | grep -E -o "^\.") >/dev/null 2>&1; then
	mem_percent="0${mem_percent}"
  fi
  if (echo -e "${swp_percent}" | grep -E -o "^\.") >/dev/null 2>&1; then
	swp_percent="0${swp_percent}"
  fi

  # output plugin format data if MODE=0
  if is_int "${mem_total}" && is_int "${mem_free}"; then
	:
  else
	EXIT_STATUS=${STATE_UNKN};
	LEVEL="unkn";
	TYPE="str";
	CONTENT="$(eval_gettext "memory total=[\${mem_total}] or memory free=[\${mem_free}] is not numberic.")";
	return
  fi

  [ "${mem_total}" == "0" ] && {
	EXIT_STATUS=${STATE_WARN};
	LEVEL="warn";
	TYPE="str";
	CONTENT="$(gettext "memory total=[0]. how could it be ?")";
	return
  }

  if is_int "${swp_total}" && is_int "${swp_free}" ; then
	:
  else
	EXIT_STATUS=${STATE_UNKN};
	LEVEL="unkn";
	TYPE="str";
	CONTENT="$(eval_gettext "swap total=[\${swp_total}] or swap free=[\${swp_free}] is not numberic.")";
	return
  fi

  [ "${swp_total}" == "0" ] && {
	EXIT_STATUS=${STATE_WARN};
	LEVEL="warn";
	TYPE="str";
	CONTENT="$(gettext "swap total=[0]. how could it be ?")";
	return
  }

  if is_float "${mem_percent}" || is_int "${mem_percent}"; then
	:
  else
	EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(eval_gettext "Retuened mem_percent should be float: [\${mem_percent}]")";
	return 
  fi

  if is_float "${swp_percent}" || is_int "${swp_percent}"; then
	:
  else
	EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(eval_gettext "Retuened swp_percent should be float: [\${swp_percent}]")";
	return 
  fi

  # output data and exit if MODE=1
  [ "${MODE}" == "1" ] && {
	echo "$((${mem_total}/1024))M $((${mem_free}/1024))M ${mem_percent}% "\
		"$((${swp_total}/1024))M $((${swp_free}/1024))M ${swp_percent}%"
	exit
  }

  oknum=0 warnnum=0 total=0 result=
  mem_total=$((${mem_total}/1024))  mem_free=$((${mem_free}/1024))
  mem_detail="$(eval_gettext "total=\${mem_total}M  free=\${mem_free}M")"
  if [ "$(echo  "${mem_percent} >= ${mem_uplimit}" | bc 2>&-)" == "1" ]; then
	((warnnum++))
	result="${result} ### $(html_red "$(eval_gettext "Memory Usage: [\${mem_percent}]% >= Uplimit: [\${mem_uplimit}%]")") ### ${mem_detail} ###"
  else
	((oknum++))
	result="${result} ### $(eval_gettext "Memory Usage: [\${mem_percent}]% <= Uplimit: [\${mem_uplimit}%]") ### ${mem_detail} ###"
  fi

  swp_total=$((${swp_total}/1024)) swp_free=$((${swp_free}/1024))
  swp_detail="$(eval_gettext "total=\${swp_total}M  free=\${swp_free}M")"
  if [ "$(echo  "${swp_percent} >= ${swp_uplimit}" | bc 2>&-)" == "1" ]; then
	((warnnum++))
	result="${result} ### $(html_red "$(eval_gettext "Swap Usage: [\${swp_percent}]% >= Uplimit: [\${swp_uplimit}%]")") ### ${swp_detail} ###"
  else
	((oknum++))
	result="${result} ### $(eval_gettext "Swap Usage: [\${swp_percent}]% <= Uplimit: [\${swp_uplimit}%]") ### ${swp_detail} ###"
  fi

  total=$((${warnnum}+${oknum}))
  if [ ${warnnum} -gt 0 ]; then
	local rsz_top_ps=$(ps -eo pid,comm,rsz|tail -n +2|sort -rn -k 3|head|sed -e 's/$/###/g' | tr -d '\n')
	local vsz_top_ps=$(ps -eo pid,comm,vsz|tail -n +2|sort -rn -k 3|head|sed -e 's/$/###/g' | tr -d '\n')
	EXIT_STATUS=${STATE_WARN};
	LEVEL="warn";
	TYPE="str";
	CONTENT="$(gettext "Memory/Swap Usage Check WARNING") | $(eval_gettext "\${warnnum}/\${total} check failed.") | ${result} ### $(gettext "RSZ_TOP:") ### ${rsz_top_ps} ### ###  $(gettext "VSZ_TOP:") ### ${vsz_top_ps}"
	((oknum++))
  else
	EXIT_STATUS=${STATE_SUCC};
	LEVEL="succ";
	TYPE="str";
	CONTENT="$(gettext "Memory/Swap Usage Check OK") | $(eval_gettext "\${oknum}/\${total} check success.") | ${result}"
  fi
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
