#!/usr/bin/env bash

# BASE_DIR DEF
[ -z ${BASE_DIR} ] && { 
        path=$( cd $(dirname $0) && pwd)
        BASE_DIR=${path%/*}
}

# === LOAD GETTEXT.SH FILE
if [ -f "/usr/bin/gettext.sh"  -a -s "/usr/bin/gettext.sh" ]; then
        source "/usr/bin/gettext.sh" 2>&1
        rc=$?
        [ "$rc" != "0" ] && {
                echo -en "{unkn}:{str}:{load [/usr/bin/gettext.sh] failed with status $rc}"
                exit 3
        }   
else
        echo -en "{unkn}:{str}:{[/usr/bin/gettext.sh] not exists or empty, maybe gettext not installed. exit}"
        exit 3
fi

# === LOAD INCLUDE FILE
if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
        source ${BASE_DIR}/bin/include 2>&- 
else    
        echo -en "{unkn}:{str}:{include file not exists or empty}"
        exit 3
fi

# === SET TEXTDOMAINDIR TEXTDOMAIN
if [ -d "${LOCALE_DIR}" -a -r "${LOCALE_DIR}" ]; then
        export TEXTDOMAINDIR="${LOCALE_DIR}"
        export TEXTDOMAIN="disk_iostat"
else    
        echo -en "{unkn}:{str}:{locale directory [${LOCALE_DIR}] not exist or accessable, exit}"
        exit 3
fi


# === SET GLOBAL LOCALE
glocale=$(get_locale disk_iostat)
if [ -z "${glocale}" ]; then
        export LANG="zh_CN.UTF-8"	# read from sysenv
elif [ "${glocale}" == "zh_CN" -o "${glocale}" == "zh_CN.UTF-8" -o "${glocale}" == "zh" ]; then
        export LANG="zh_CN.UTF-8"
elif [ "${glocale}" == "en_US" -o "${glocale}" == "en_US.UTF-8" -o "${glocale}" == "en" ]; then
        export LANG="en_US.UTF-8"
else
        export LANG="zh_CN.UTF-8"
fi


show_help(){
cat <<EOF
Arguments:   {d|data|h|help}

Usage	 :   data

Output   :   {devpath} -> {mpoint} : %{util}
Example  :   
/dev/sda1 -> /boot : 0.006%
/dev/mapper/VolGroup-lv_root -> / : 81.08%
EOF
exit 0;
}
MODE=0
[ "$1" == "data" -o "$1" == "d" ] && MODE=1
[ "$1" == "help" -o "$1" == "h" ] && show_help;


# Return Codes
STATE_SUCC=0
STATE_WARN=1
STATE_CRIT=2
STATE_UNKN=3
STATE_NOOP=4
STATE_NOTIFY=5

# Set Default
EXIT_STATUS=0
LEVEL=    	### { succ | warn | crit | unkn | noop | notify }
TYPE=    	### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
if [ "${MODE}" == "1" ]; then
	dev_list=$2
else
	dev_list=$( read_mole_config disk_iostat dev_list )
	util_uplimit=$( read_mole_config disk_iostat util_uplimit )
fi

# if null return STATE_UNKN.

# if null or invalid set default.
[ -z "${util_uplimit}" -o ! -z "${util_uplimit//[0-9]}" ] && util_uplimit=70

# check function here
check(){

  if [ -z "${dev_list}" ]; then
	EXIT_STATUS=${STATE_UNKN};
	LEVEL="unkn";
	TYPE="str";
	CONTENT="$(gettext "config {dev_list} empty, nothing to do.")";
	return
  fi

  if [ ! -x "/usr/bin/iostat" ]; then
	EXIT_STATUS=${STATE_UNKN};
	LEVEL="unkn";
	TYPE="str";
	CONTENT="$(gettext "Util: [/usr/bin/iostat] not prepared.")";
	return
  fi

  # collect data
  local iostat_data=$( /usr/bin/iostat -d -x ${dev_list} 1 5 2>&1 )
  
  oknum=0 warnnum=0 result=
  for dev in ${dev_list}
  do
	# skip device that not exists
	[ -e "${dev}" ] || continue

	if [ -L "${dev}" ]; then	# in case of lvm
		dev_tmpname="$(/bin/readlink ${dev} 2>&-)"
		devname="${dev_tmpname##*/}"
	else
		devname="${dev##*/}"
	fi

	util=$( echo -e "${iostat_data}" | /bin/awk '($1~/^'${devname}'\>/){x+=$NF} END{print x/5}' 2>&- )
	[ -z "${util}" -o ! -z "${util//[0-9.]}" ] && util=0

	mpoint=$( /bin/awk -v d="${dev}" '($1==d){print $2}' /etc/mtab 2>&- )
	[ -z "${mpoint}" ] && mpoint="NULL"

  	# output data and exit if MODE=1
  	[ "${MODE}" == "1" ] && {
		echo "${dev} -> ${mpoint} : ${util}%"
		continue
  	}

  	if [ "$(echo  "${util} >= ${util_uplimit}" | bc 2>&-)" == "1" ]; then
		((warnnum++))
		result="${result} $(html_red "$(eval_gettext "\${dev} (\${mpoint}) io busy percent: [\${util}%] >= uplimit: [\${util_uplimit}%]")" ) ###"
  	else
		((oknum++))
		result="${result} $(eval_gettext "\${dev} (\${mpoint}) io busy percent: [\${util}%] <= uplimit: [\${util_uplimit}%]") ###"
  	fi
  done

  # exit if MODE=1
  [ "${MODE}" == "1" ] && exit

  total=$((${warnnum}+${oknum}))
  if [ ${warnnum} -gt 0 ]; then
	EXIT_STATUS=${STATE_WARN};
	LEVEL="warn";
	TYPE="str";
	CONTENT="$(gettext "IOStat Check WARNING") | $(eval_gettext "\${warnnum}/\${total} check failed.") | ${result}"
  else
	EXIT_STATUS=${STATE_SUCC};
	LEVEL="succ";
	TYPE="str";
	CONTENT="$(gettext "IOStat Cehck OK") | $(eval_gettext "\${oknum}/\${total} check success.") | ${result}"
  fi
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
