#!/usr/bin/env perl

our $basedir = '/usr/local/esop/agent/mole';
our $mole = "$basedir/mole";

BEGIN {
  my $basedir = '/usr/local/esop/agent/mole';
  my $pllib_dir = "$basedir/opt/plmods";
  my @incs = (    # set additional path
        # rhel5 32bit
        $pllib_dir.'/lib/perl5/',
        $pllib_dir.'/lib/perl5/5.8.8/',
        $pllib_dir.'/lib/perl5/site_perl/',
        $pllib_dir.'/lib/perl5/site_perl/5.8.8/',
        # rhel5 64bit
        $pllib_dir.'/lib64/perl5/',
        $pllib_dir.'/lib64/perl5/5.8.8/',
        $pllib_dir.'/lib64/perl5/site_perl/',
        $pllib_dir.'/lib64/perl5/site_perl/5.8.8/',
        # rhel6 32bit
        $pllib_dir.'/lib/perl5/',
        # rhel6 64bit
        $pllib_dir.'/lib64/perl5/',
  );   

  push @INC, @incs;
};

use warnings;
use strict;
use utf8;
use JSON;
# use Smart::Comments;
binmode(STDIN, ":encoding(utf8)");
binmode(STDOUT, ":encoding(utf8)");

$| = 1;

# return codes
our ($state_succ,$state_warn,$state_crit,$state_unkn,$state_noop,$state_notify) = (0,1,2,3,4,5);

# return stuff
our ($rc, $result) = (0,'');

our $filename = (split /\//, __FILE__)[-1];

#
#  BEGIN to COLLECT eYou INFORMATION 
#

my $mail_license = '{}';
my $php = '/usr/local/eyou/mail/opt/bin/php';
my $decoder = '/usr/local/esop/agent/mole/php/mail/mail_license.php';
if (-f $php && -x $php && -f $decoder && -x $decoder) {
	open my $fh, "sudo -u eyou $php $decoder 2>&-|";
	if($fh){
		while(<$fh>){
			chomp; $mail_license = $_ unless (m/\A\s*\Z/);
			last;
		}
	}
}

# PREPARE LAST RESULT HASH
my %result = (
        'mail_license'          => $mail_license,
);
### %result

$result = JSON->new->utf8(1)->ascii(1)->encode(\%result);
print "{succ}:{str}:{$filename|$filename|$result}";
exit $state_succ;
