#!/usr/bin/env bash


# BASE_DIR DEF
[ -z ${BASE_DIR} ] && { 
        path=$( cd $(dirname $0) && pwd)
        BASE_DIR=${path%/*}
}

# === LOAD GETTEXT.SH FILE
if [ -f "/usr/bin/gettext.sh"  -a -s "/usr/bin/gettext.sh" ]; then
        source "/usr/bin/gettext.sh" 2>&1
        rc=$?
        [ "$rc" != "0" ] && {
                echo -en "{unkn}:{str}:{load [/usr/bin/gettext.sh] failed with status $rc}"
                exit 3
        }
else
        echo -en "{unkn}:{str}:{[/usr/bin/gettext.sh] not exists or empty, maybe gettext not installed. exit}"
        exit 3
fi

# === LOAD INCLUDE FILE
if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
        source ${BASE_DIR}/bin/include 2>&- 
else        
        echo -en "{unkn}:{str}:{include file not exists or empty}"
        exit 3
fi

# === SET TEXTDOMAINDIR TEXTDOMAIN
if [ -d "${LOCALE_DIR}" -a -r "${LOCALE_DIR}" ]; then
        export TEXTDOMAINDIR="${LOCALE_DIR}"
        export TEXTDOMAIN="emp_smtpauth_limit"
else        
        echo -en "{unkn}:{str}:{locale directory [${LOCALE_DIR}] not exist or accessable, exit}"
        exit 3
fi

# === SET GLOBAL LOCALE
glocale=$(get_locale emp_smtpauth_limit)
if [ -z "${glocale}" ]; then
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
elif [ "${glocale}" == "zh_CN" -o "${glocale}" == "zh_CN.UTF-8" -o "${glocale}" == "zh" ]; then
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
elif [ "${glocale}" == "en_US" -o "${glocale}" == "en_US.UTF-8" -o "${glocale}" == "en" ]; then
        export LANG="en_US.UTF-8"  LC_ALL="en_US.UTF-8"
else
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
fi


show_help(){
cat <<EOF
Arguments:   {d|data|h|help}

Usage:	 data 

Output:   
EOF
exit 0;
}
MODE=0
[ "$1" == "data" -o "$1" == "d" ] && MODE=1
[ "$1" == "help" -o "$1" == "h" ] && show_help;


# Return Codes
STATE_SUCC=0
STATE_WARN=1
STATE_CRIT=2
STATE_UNKN=3
STATE_NOOP=4
STATE_NOTIFY=5

# Set Default
EXIT_STATUS=0
LEVEL=    	### { succ | warn | crit | unkn | noop | notify }
TYPE=   	### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
if [ "${MODE}" == "1" ]; then
	action="$2"
else
	mysqlcli_path=$( read_mole_config emp_smtpauth_limit mysqlcli_path )
	usrmysql_conn_conf=$( read_mole_config emp_smtpauth_limit usrmysql_conn_conf )
	logmysql_conn_conf=$( read_mole_config emp_smtpauth_limit logmysql_conn_conf )
	mysql_time_out=$( read_mole_config emp_smtpauth_limit mysql_time_out )
	smtp_auth_limit=$( read_mole_config emp_smtpauth_limit smtp_auth_limit )
	smtp_white_list=$( read_mole_config emp_smtpauth_limit smtp_white_list )
	action_pipe_file=$( read_mole_config emp_smtpauth_limit action_pipe_file )
	action_tag_path=$( read_mole_config emp_smtpauth_limit action_tag_path )
	user_max_repeat=$( read_mole_config emp_smtpauth_limit user_max_repeat )
fi

# if null return STATE_UNKN.

# if null or invalid set default.
is_int "${mysql_time_out}"  || mysql_time_out=10
is_int "${user_max_repeat}" || user_max_repeat=1
[ -z "${action_pipe_file}" ] && action_pipe_file="/var/tmp/${0##*/}.pipe"
[ -z "${action_tag_path}" ] && action_tag_path="/var/tmp/${0##*/}.tag/"

# pre set {smtp_white_list}
if [ -f "/${smtp_white_list##*file:}" ] && [ -s "/${smtp_white_list##*file:}" ]; then
	smtp_white_list=$(awk '($0!~/^[ \t]*#/) { for(i=1;i<=NF;i++) {printf "%s ",$i} }' "/${smtp_white_list##*file:}")
elif [ -f "${BASE_DIR}/${smtp_white_list##*file:}" ] && [ "${BASE_DIR}/${smtp_white_list##*file:}" ]; then
        smtp_white_list=$(awk '($0!~/^[ \t]*#/) { for(i=1;i<=NF;i++) {printf "%s ",$i} }' "${BASE_DIR}/${smtp_white_list##*file:}")
else
        [ -z "${smtp_white_list}" ] && smtp_white_list="white_user@list.here"
fi


# check function here
check(){

  [ -z "${mysqlcli_path}" ] && {
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(gettext "mysqlcli_path not defined.")";
        return
  }

  [ -f "${mysqlcli_path}" -a -x "${mysqlcli_path}" ] || {
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(eval_gettext "utitile: [\${mysqlcli_path}] not prepared.")";
        return
  }

  [ -z "${usrmysql_conn_conf}" ] && {
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(gettext "usrmysql_conn_conf not defined.")";
        return
  }

  sepnum=$(echo -e "${usrmysql_conn_conf}" | awk -F"," 'END{print --NF}')
  if [ "${sepnum}" != "4" ]; then
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(eval_gettext "usrmysql_conn_conf [\${usrmysql_conn_conf}] is invalid.")";
        return
  else
	mysql_host="$(echo -e "${usrmysql_conn_conf}"|awk -F"," '{print $1}')"
        mysql_port="$(echo -e "${usrmysql_conn_conf}"|awk -F"," '{print $2}')"
        mysql_user="$(echo -e "${usrmysql_conn_conf}"|awk -F"," '{print $3}')"
        mysql_pass="$(echo -e "${usrmysql_conn_conf}"|awk -F"," '{print $4}')"
	usr_database="$(echo -e "${usrmysql_conn_conf}"|awk -F"," '{print $5}')"

	if [ -z "${mysql_pass}" ]; then
		usrmysql="${mysqlcli_path} -h ${mysql_host} -P ${mysql_port} -u${mysql_user} --connect-timeout ${mysql_time_out}  -D ${usr_database} "
	else
		usrmysql="${mysqlcli_path} -h ${mysql_host} -P ${mysql_port} -u${mysql_user} -p${mysql_pass} --connect-timeout ${mysql_time_out} -D ${usr_database} "
	fi
  fi

  [ -z "${logmysql_conn_conf}" ] && {
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(gettext "logmysql_conn_conf not defined.")";
        return
  }

  sepnum=$(echo -e "${logmysql_conn_conf}" | awk -F"," 'END{print --NF}')
  if [ "${sepnum}" != "4" ]; then
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(eval_gettext "logmysql_conn_conf [\${logmysql_conn_conf}] is invalid.")";
        return
  else
	mysql_host="$(echo -e "${logmysql_conn_conf}"|awk -F"," '{print $1}')"
        mysql_port="$(echo -e "${logmysql_conn_conf}"|awk -F"," '{print $2}')"
        mysql_user="$(echo -e "${logmysql_conn_conf}"|awk -F"," '{print $3}')"
        mysql_pass="$(echo -e "${logmysql_conn_conf}"|awk -F"," '{print $4}')"
	log_database="$(echo -e "${logmysql_conn_conf}"|awk -F"," '{print $5}')"

	if [ -z "${mysql_pass}" ]; then
		logmysql="${mysqlcli_path} -h ${mysql_host} -P ${mysql_port} -u${mysql_user} --connect-timeout ${mysql_time_out}  -D ${log_database} "
	else
		logmysql="${mysqlcli_path} -h ${mysql_host} -P ${mysql_port} -u${mysql_user} -p${mysql_pass} --connect-timeout ${mysql_time_out} -D ${log_database} "
	fi
  fi

  [ -d "${action_tag_path}" -a -x "${action_tag_path}" ] ||  {
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(eval_gettext "directory: [\${action_tag_path}] not prepared.")";
        return
  }

  is_int "${smtp_auth_limit}" || {
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(eval_gettext "smtp_auth_limit: [\${smtp_auth_limit}] not integer.")";
        return
  }

  local result=
  local warnnum=0  unknnum=0
  
  locklst_tmpfile="/var/tmp/${0##*/}.locked.lst.tmp"
  authlst_tmpfile="/var/tmp/${0##*/}.authtop.lst.tmp"
  errstuff=$( ${usrmysql} -s -e "SELECT concat(acct_key.acct_name,'@',domain_key.domain_name) FROM acct_key,domain_key,user_basic WHERE acct_key.domain_id=domain_key.domain_id AND acct_key.acct_id=user_basic.acct_id AND user_basic.has_smtp=0 AND user_basic.has_remote=0 AND acct_key.acct_type=0 AND domain_key.domain_type=0; " 2>&1 1>"${locklst_tmpfile}" )
  if [ "$?" != "0" ]; then
	((unknnum++))
	errstuff=$( (echo -e "${errstuff}" | sed -e '/password on the command line/d' | tr -d '\r\n') 2>&- )
	result="${result} $(html_red "$(gettext "Read Locked Users from User Mysql Failed:") [${errstuff}]") ### "
  else
	start=$( date -d "" +%s 2>&-)
	end=$(( $start + 86400 ))
	top_limit=100
	errstuff=$( $logmysql -s -e "SELECT count(*), concat(real_acct_name,'@',real_domain_name) FROM log_auth WHERE auth_time between '${start}' AND '${end}' AND auth_type=1 AND result=0 GROUP BY 2 ORDER BY 1 DESC LIMIT $top_limit;" 2>&1 1>"${authlst_tmpfile}" )
	if [ "$?" != "0" ]; then
		((unknnum++))
		errstuff=$( (echo -e "${errstuff}" | sed -e '/password on the command line/d' | tr -d '\r\n') 2>&- )
		result="${result} $(html_red "$(gettext "Read SMTP Auth Top Records from Log Mysql Failed:") [${errstuff}]") ### "
	else
		# locked user saved in file: {locklst_tmpfile}
		# smtpauth top list saved in file: {authlst_tmpfile}
		smtp_lock_list=$(cat "${locklst_tmpfile}" 2>&-)
		# will save spamer user into file: {action_pipe_file}
		: > "${action_pipe_file}" 2>&-
		today=$(date +%Y%m%d 2>&-)
		while read number email
		do
			lock_tag="${action_tag_path}/${email}_${today}"
			if ( echo -e "${smtp_lock_list}" | grep -E "\<${email}\>" ) >/dev/null 2>&1 ; then
				result="${result} ${number} ${email} ($(gettext "already locked")) ### "
			elif ( echo -e "${smtp_white_list}" | grep -E "\<${email}\>" ) >/dev/null 2>&1 ; then
				result="${result} ${number} ${email} ($(gettext "unlimited user")) ### "
			elif [ "${number}" -ge "${smtp_auth_limit}" ]; then
				if [ -f "${lock_tag}" -a -s "${lock_tag}" ]; then
					locknum=$(head -n1 "${lock_tag}" 2>&-)
					is_int "${locknum}" || locknum=0
					if [ "${locknum}" -ge "${user_max_repeat}" ]; then
						result="${result} ${number} ${email} ($(eval_gettext "already lock for \${locknum} times today")) ### "
					else
						((warnnum++))
						result="${result} $(html_red "${number} ${email} ($(eval_gettext "spamer, already lock for \${locknum} times today"))") ### "
						echo -e "${number} ${email} ${locknum}" >> "${action_pipe_file}"
					fi
				else
					((warnnum++))
					result="${result} $(html_red "${number} ${email} ($(gettext "spamer"))") ### "
					echo -e "${number} ${email} 0" >> "${action_pipe_file}"
				fi
			else
				result="${result} ${number} ${email} ### "
			fi
		done < "${authlst_tmpfile}"
	fi
  fi

  # exit if MODE=1
  [ "${MODE}" == "1" ] && exit;

  if [ "${warnnum}" -gt "0" ]; then
	EXIT_STATUS=${STATE_WARN};
	LEVEL="warn";
	TYPE="str";
	CONTENT="$(gettext "SMPT Auth Limit Check WARNING") | $(eval_gettext "\${warnnum} Users SMTP Auth Exceed") | ${result} "
  else
	if [ "${unknnum}" -gt "0" ]; then
		EXIT_STATUS=${STATE_UNKN};
		LEVEL="unkn";
		TYPE="str";
		CONTENT="$(gettext "SMTP Auth Limit Check UNKNOWN") | $(gettext "Something Unknown Happened") | ${result} "
	else
		EXIT_STATUS="${STATE_SUCC}"
		LEVEL="succ"
		TYPE="str"
		CONTENT="$(gettext "SMTP Auth Limit Check OK") | $(gettext "No Users SMTP Auth Exceed") | ${result} "
	fi
  fi
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
