#!/usr/bin/env bash

# BASE_DIR DEF
[ -z ${BASE_DIR} ] && { 
        path=$( cd $(dirname $0) && pwd)
        BASE_DIR=${path%/*}
}

# === LOAD GETTEXT.SH FILE
if [ -f "/usr/bin/gettext.sh"  -a -s "/usr/bin/gettext.sh" ]; then
        source "/usr/bin/gettext.sh" 2>&1
        rc=$?
        [ "$rc" != "0" ] && {
                echo -en "{unkn}:{str}:{load [/usr/bin/gettext.sh] failed with status $rc}"
                exit 3
        }   
else
        echo -en "{unkn}:{str}:{[/usr/bin/gettext.sh] not exists or empty, maybe gettext not installed. exit}"
        exit 3
fi

# === LOAD INCLUDE FILE
if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
        source ${BASE_DIR}/bin/include 2>&- 
else    
        echo -en "{unkn}:{str}:{include file not exists or empty}"
        exit 3
fi

# === SET TEXTDOMAINDIR TEXTDOMAIN
if [ -d "${LOCALE_DIR}" -a -r "${LOCALE_DIR}" ]; then
        export TEXTDOMAINDIR="${LOCALE_DIR}"
        export TEXTDOMAIN="http_svr"
else    
        echo -en "{unkn}:{str}:{locale directory [${LOCALE_DIR}] not exist or accessable, exit}"
        exit 3
fi


# === SET GLOBAL LOCALE
glocale=$(get_locale http_svr)
if [ -z "${glocale}" ]; then
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
elif [ "${glocale}" == "zh_CN" -o "${glocale}" == "zh_CN.UTF-8" -o "${glocale}" == "zh" ]; then
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
elif [ "${glocale}" == "en_US" -o "${glocale}" == "en_US.UTF-8" -o "${glocale}" == "en" ]; then
        export LANG="en_US.UTF-8"  LC_ALL="en_US.UTF-8"
else
        export LANG="zh_CN.UTF-8"  LC_ALL="zh_CN.UTF-8"
fi


show_help(){
cat <<EOF
Arguments:   {d|data|h|help}  {addr_port}  {tmout}
{addr_port} format:
  [http|https]:ip:port

Usage:   data  "http:127.0.0.1:80  https:mail.eyou.net:443"  10

Output:   
{addr}:{port}  {http_code} {time_total}s {size_download}Bytes

127.0.0.1:80 200 0.008s 12Bytes
mail.eyou.net:443 200 0.108s 24736Bytes
EOF
exit 0;
}

MODE=0
[ "$1" == "data" -o "$1" == "d" ] && MODE=1
[ "$1" == "help" -o "$1" == "h" ] && show_help;


# Return Codes
STATE_SUCC=0
STATE_WARN=1
STATE_CRIT=2
STATE_UNKN=3
STATE_NOOP=4
STATE_NOTIFY=5

# Set Default
EXIT_STATUS=0
LEVEL=    	### { succ | warn | crit | unkn | noop | notify }
TYPE=    	### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
if [ "${MODE}" == "1" ]; then
        addr_port="$2"
	time_out="$3"
else   
	addr_port=$( read_mole_config http_svr addr_port )
	time_out=$( read_mole_config http_svr time_out )
fi

# if null return STATE_UNKN.

# if null or invalid set default.
[ -z "${addr_port}" ] && addr_port="http:127.0.0.1:80"
[ -z "${time_out}" -o ! -z "${time_out//[0-9]}" ] && time_out=10

# check function here
check(){
  [ -f "/usr/bin/curl" -a -x "/usr/bin/curl" ] || {
        EXIT_STATUS=${STATE_UNKN};
        LEVEL="unkn";
        TYPE="str";
        CONTENT="$(gettext "utilite [/usr/bin/curl] not prepared.")"
        return
  }

  local total=  err_num=0  result=
  for x in `echo "${addr_port}"`;
  do
	local addr=  port=  str1=  str2=
	prot=$(echo "${x}" | awk -F: '{print $1}')
	addr=$(echo "${x}" | awk -F: '{print $2}')
	port=$(echo "${x}" | awk -F: '{print $NF}')
	[ "${prot}" == "https" ] && {
	arr=($(curl -s -k -o /dev/null -w "%{http_code} %{time_total}s %{size_download}Bytes" "${prot}://${addr}:${port}" 2>&1))
	}
	[ "${prot}" == "http" ] && {
	arr=($(curl -s -o /dev/null -w "%{http_code} %{time_total}s %{size_download}Bytes" "${prot}://${addr}:${port}" 2>&1))
	}
	# output data and exit if MODE=1
	[ "${MODE}" == "1" ] && {
		echo "${addr}:${port} ${arr[*]}"
		continue
	}
	code=${arr[0]}; time=${arr[1]}; pagesize=${arr[2]}
  	if [ "${arr[0]}" == "200" ]; then
		result=" ${result} $(eval_gettext "check [\${x}] return [code=\${code}, time=\${time}, pagesize=\${pagesize}]") ### "
  	else
		((err_num++))
		result=" ${result} $(html_red "$(eval_gettext "check [\${x}] return [code=\${code}, time=\${time}, pagesize=\${pagesize}]")") ### "
  	fi
	((total++))
  done

  # exit if MODE=1
  [ "${MODE}" == "1" ] && exit

  [ "${err_num}" == "0" ] && {
	EXIT_STATUS=${STATE_SUCC};
	LEVEL="succ";
	TYPE="str";
	CONTENT="$(gettext "HTTP SVR OK") | $(eval_gettext "\${total}/\${total} http check success.") | "${result}" "
  } || {
	EXIT_STATUS=${STATE_CRIT};
	LEVEL="crit";
	TYPE="str";
	CONTENT="$(gettext "HTTP SVR CRITICAL") | $(eval_gettext "\${err_num}/\${total} http check failed.") | "${result}" "
  }
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
