#!/bin/bash

Name="企业邮箱"
Admins=" admin@yourdomain.com "
Limit=2
White_List=" white@here.list "
Lock_Spamer=yes
Mod_Password=no
Search_Num=15
Repeat_Lock_Num=1



_tmp=$(for ((x=1;x<=8;x++));do echo -e "$(cat /proc/sys/kernel/random/uuid|cut -c1)\c ";done)
Pass_Phrase=${_tmp}
#echo $Pass_Phrase ; echo $Pass_Phrase ; echo $Pass_Phrase


# =================   Initialization  ============================

workdir="/usr/local/eyou/mail/log/smtpmon"
lock_tagdir="$workdir/lock_tag"
mkdir -p $lock_tagdir ; cd $workdir
touch $workdir/smtpmon.log
[ $(du -sm $workdir/smtpmon.log|awk '{print $1}') -ge 1800 ] && mv $workdir/smtpmon.log $workdir/smtpmon.log.$(date +%s) && touch $workdir/smtpmon.log

date=$(date +%F"-"%T)
today=$(date +%Y%m%d)

config="/usr/local/eyou/mail/etc/eyou_mail.ini"
if [ -s $config ] ; then
	Domain=$(awk -F "=" '/^server_me\>/ {print $2}' $config | sed -e 's/"//g; s/^[ \t]*//g')
else
        echo "$config not exists or empty. exit" 
        exit 1
fi

Mysql="/usr/local/eyou/mail/opt/mysql/bin/mysql -D eyou_mail -S /usr/local/eyou/mail//run/em_mysql.sock   -h127.1 "
Mysql1="/usr/local/eyou/mail/opt/mysql/bin/mysql -D eyou_mail_log -S /usr/local/eyou/mail//run/em_mysql.sock  -P3326  -h127.1 "

echo -e "\n\n  ====  $date   ====  \n\n" >> smtpmon.log


# =================  Functions Definations ========================

show_usage() {

	echo -e "\n\n\t\t Usage: sh ${0##*/} -l -L -h [ -y yyyy  -m mm  -d dd ]  \n\n"
	exit 0
}

red_it() {
        string=$*;
        echo -e "\033[1;31m$string\033[0m\c "
}

green_it() {
        string=$*;
        echo -e "\033[1;32m$string\033[0m\c "
}

yellow_it() {
        string=$*;
        echo -e "\033[1;33m$string\033[0m\c "
}

get_locked_user() {

        $Mysql -s -e "select acct_name,domain_name from acct_key,domain_key  where domain_key.domain_id=acct_key.domain_id and acct_key.acct_id in (select acct_id from user_basic where has_smtp=0 and has_remote=0);" | awk '{printf "%s@%s\n",$1,$2}'

}

# Example:      get_locked_user         :has_smtp=0 and has_remote=0


get_smtp_auth() {

        year=$1; month=$2; day=$3

        if [ -n "$year" -a -n "$month" -a -n "$day" ] ; then
                Start=$(date "-d $year-$month-$day 00:00:00" +%s)
                Offset="86400"
        elif [  -n "$year" -a -n "$month" -a "$day" == "" ] ; then
                Start=$(date "-d $year-$month-01 00:00:00" +%s)
                Offset="2592000"
        fi

        End=$( echo " $Start + $Offset "  | bc )

        # echo $Start ; echo $Offset ; echo $End

        $Mysql1 -s -e "select real_acct_name,real_domain_name from log_auth where auth_time between '$Start' and '$End' and auth_type=1 and result=0;" |sort | uniq -c | sort -rn | head -n $Search_Num

}

#Example:       get_smtp_auth  yyyy mm dd       :Display yyyy-mm-dd or yyyy-mm SMTP Auth Top List
#Example:	will be called by get_spamer


get_spamer() {

opt=$1;  get_locked_user > lock.list

case $opt in 
"-v")

        get_smtp_auth  `date +%Y` `date +%m` `date +%d` |  while read  -a line
        do
                num=${line[0]}; uid=${line[1]}; domain=${line[2]}; mbox=${line[1]}@${line[2]}
		lock_tag="${lock_tagdir}/${uid}@${domain}_${today}"

		# echo $num $uid $domain $mbox $lock_tag

                if [ $num -ge $Limit ] ; then

                        if grep -E "\<${mbox}\>" lock.list > /dev/null 2>&1 ; then
                                echo -e "\t\t ${line[*]}    (already locked)"

                        elif ( echo "$White_List" | grep -E "\<${mbox}\>" ) >/dev/null 2>&1 ; then
                                echo -e "\t\t ${line[*]}    (white list member)"

			elif [ -s "$lock_tag" ] ; then
				if [ $(cat $lock_tag) -ge $Repeat_Lock_Num ]; then
					echo -e "\t\t ${line[*]}    (reach repeat lock limit)"
				else
					echo -e "\t\t $(red_it "${line[*]}")    $(yellow_it "  spamer") : $(cat $lock_tag)"
				fi
                        else
                                echo -e "\t\t $(red_it "${line[*]}")    $(yellow_it "    spamer")"  
                        fi
                else
                        echo -e "\t\t ${line[*]}"
                fi
        done 

        ;;

"-s")

        get_smtp_auth  `date +%Y` `date +%m` `date +%d` |  while read  -a line
        do
                num=${line[0]}; uid=${line[1]}; domain=${line[2]}; mbox=${line[1]}@${line[2]}
                lock_tag="${lock_tagdir}/${uid}@${domain}_${today}"

		# echo $num $uid $domain $mbox $lock_tag

                if [ $num -ge $Limit ] ; then

			if grep -E "\<${mbox}\>" lock.list > /dev/null 2>&1 ; then
				continue

			elif ( echo "$White_List" | grep -E "\<${mbox}\>" ) >/dev/null 2>&1 ; then
				continue

			elif [ -s "$lock_tag" ] ; then
				if [ $(cat $lock_tag) -ge $Repeat_Lock_Num ] ; then
					continue
				else
					echo $num $uid $domain
				fi
			else
				echo $num $uid $domain
			fi
		else
			continue
                fi
        done

        ;;

esac

}

#Example:       get_spamer  -v          :Display SMTP Auth Info
#Example:       get_spamer  -s          :Display Spamer List


gen_lock_csv() {

        uid=$1 ; domain=$2 ; password=$3

        if [ "$password" != "" ] ; then
                echo ":cond:acct_name,:cond:domain_name,user_basic:has_smtp,user_basic:has_remote,user_basic:password"
                echo "\"${uid}\",\"${domain}\",\"0\",\"0\",\"${Pass_Phrase}\"" 
        else 
                echo ":cond:acct_name,:cond:domain_name,user_basic:has_smtp,user_basic:has_remote" 
                echo "\"${uid}\",\"${domain}\",\"0\",\"0\"" 
        fi
}

#Example:       only called by lock_user

lock_user() {

        uid=$1; domain=$2 ; password=$3

        gen_lock_csv  "${uid}" "${domain}" "${password}" > lock.csv ;

        if [ -s lock.csv ] ; then

                cat lock.csv >> smtpmon.log  2>&1  ; echo >> smtpmon.log

                sudo -u eyou /usr/local/eyou/mail/app/sbin/em_control  -m user::mod_user -f lock.csv -t c >> smtpmon.log 2>&1

                lock_tag="${lock_tagdir}/${uid}@${domain}_${today}"

                [ ! -s $lock_tag ] && Num=1 || Num=$((  $(cat $lock_tag) + 1 ))

                echo "repeat lock num:    $Num" >> smtpmon.log

                echo $Num > $lock_tag

        fi

        rm -f lock.csv

}

# Example:              lock_user  uid domain [pasword]


send_single_alert_mail(){

        send_to=$1; num=$2 ; uid=$3 ; domain=$4
	[ "${Name}" == "" ] && Name=${Domain}

        > alert.eml
        echo "From:Antispam@"$Domain" " >> alert.eml
        echo "To:$send_to" >> alert.eml
        echo "Subject: "$Name" 邮件系统发现可疑帐号:" >> alert.eml
        echo "date: $(date +%F" # "%T)" >> alert.eml
        echo "" >> alert.eml && echo "" >> alert.eml
        echo "可疑帐号今日验证情况如下: 验证次数 用户名 域名" >> alert.eml
        echo "" >> alert.eml && echo "" >> alert.eml
	echo "   $num  $uid  $domain  " >> alert.eml
        echo "" >> alert.eml && echo "" >> alert.eml
        echo "该帐号可能是采用了弱口令被猜解利用群发垃圾邮件" >> alert.eml
        echo "" >> alert.eml 
		if [ "$Lock_Spamer" == yes ] ; then
				echo "禁用了该帐号的SMTP和邮件外发功能" >> alert.eml
				[ "$Mod_Password" == yes ] && echo "修改该帐号密码为${Pass_Phrase}" >> alert.eml
		fi
        echo "" >> alert.eml 
        echo "请及时通知用户加强口令安全" >> alert.eml
	
	iconv -f utf8 -t gbk $workdir/alert.eml -o $workdir/alert.eml.gbk

        /usr/local/eyou/mail/app/bin/em_sendmail  -f Antispam@"$Domain" $send_to -F $workdir/alert.eml.gbk
        cat $workdir/alert.eml >> smtpmon.log

}

#Example:	send_single_alert_mail   send_to  num  uid  domain	:called by send_alert_mail

send_alert_mail() {
	
	num=$1; uid=$2; domain=$3
	
	for admin in `echo ${Admins}`
	do
		send_single_alert_mail  $admin  $num  $uid  $domain
	done
	
	send_single_alert_mail  ${uid}@${domain}  $num  $uid  $domain
	send_single_alert_mail  support@${Domain} $num  $uid  $domain
}

#Example:	send_alert_mail	  num  uid  domain	


# =================   Main Body  ============================

# -----------  Debug Functions Here ------------
#
# get_locked_user  ; exit 
# get_smtp_auth  2011 05  ; exit 
# get_smtp_auth  2011 05 23  ; exit 
# get_spamer  -v ; exit 
# get_spamer  -s ; exit
# lock_user eyoutest jnnc.com ; exit
# lock_user eyoutest jnnc.com "&^&*&^*"  ; exit
# send_single_alert_mail  zhangguangzheng@eyou.net  10000 spamer abc.com ; exit
# send_alert_mail  2222 I-am-spamer  222.com  ; exit


while getopts y:m:d:Llh opt
do
	
	case $opt in 
	
	"y")
		_year=$OPTARG	;;
	"m")
		_month=$OPTARG	;;
	"d")
		_day=$OPTARG	;;
	"L")
		echo -e "\n\n\t `green_it "Already Locked Users:"` \n\n"
		get_locked_user	| sed -e 's/^/\t/'
		echo -e "\n\n"	
		exit 0			;;

	"l")
		echo -e "\n\n\t\t `green_it "Today SMTP Auth Info:"` \n\n"
		get_spamer -v
		echo -e "\n\n"  
		exit 0			;;

	"h")
		show_usage	;;
	"*")
		show_usage	;;

	esac

done


# echo ${_year}  ${_month}  ${_day}  ; exit 

if [ -n "$_year" -a -n "$_month" -a -n "$_day" ]; then
	
	echo -e "\n\n\t `green_it "$_year-$_month-$_day SMTP Auth Info:"` \n\n"
	get_smtp_auth $_year $_month $_day | column -t | sed -e 's/^/\t/'
	echo -e "\n\n"
	exit 0 

elif [  -n "$_year" -a -n "$_month" ] ; then

	echo -e "\n\n\t `green_it "$_year-$_month SMTP Auth Info:"` \n\n"
	get_smtp_auth $_year $_month | column -t | sed -e 's/^/\t/'
	echo -e "\n\n"
	exit 0 

fi


# get_spamer -s  ; exit 

get_spamer -s | while read _num _uid _domain
do

        if [ $Lock_Spamer == yes ] ; then

             [ $Mod_Password == yes ] && lock_user "${_uid}" "${_domain}" "${Pass_Phrase}" || lock_user "${_uid}" "${_domain}"

        fi

        send_alert_mail ${_num} ${_uid} ${_domain}

done
