#!/usr/bin/env perl
use warnings;
use strict;
use utf8;
use JSON;
# use Smart::Comments;
binmode(STDIN, ":encoding(utf8)");
binmode(STDOUT, ":encoding(utf8)");

$| = 1;

# return codes
our ($state_ok,$state_warn,$state_crit,$state_unkn,$state_noop) = (0,1,2,3,4);

# return stuff
our ($rc, $result) = (0,'');

our $filename = (split /\//, __FILE__)[-1];

#
#  BEGIN to COLLECT SYSTEM INFORMATION 
#
my %load_avg = (
  '1min'	=> '',
  '5min'	=> '',
  '15min'	=> '',
);

my %online_user = (

);

my %runtime = (
  'boottime'	=> '',
  'runtime'	=> '',
  'idletime'	=> '',
);

my %mem_usage = (
  'mem_usage'	=> '',
  'swp_usage'	=> '',
);

my @prt_usgage = '';



# PREPARE LAST RESULT HASH
my %result = (
);
### %result

$result = JSON->new->utf8(1)->ascii(1)->encode(\%result);
print "{ok}:{str}:{$filename|$filename|$result}";
exit $state_ok;
