#!/usr/bin/env perl

our $basedir = '/usr/local/esop/agent/mole';
our $mole = "$basedir/sbin/mole";

BEGIN {
  my $basedir = '/usr/local/esop/agent/mole';
  my $pllib_dir = "$basedir/opt/plmods";
  my @incs = (    # set additional path
        # rhel5 32bit
        $pllib_dir.'/lib/perl5/',
        $pllib_dir.'/lib/perl5/5.8.8/',
        $pllib_dir.'/lib/perl5/site_perl/',
        $pllib_dir.'/lib/perl5/site_perl/5.8.8/',
        # rhel5 64bit
        $pllib_dir.'/lib64/perl5/',
        $pllib_dir.'/lib64/perl5/5.8.8/',
        $pllib_dir.'/lib64/perl5/site_perl/',
        $pllib_dir.'/lib64/perl5/site_perl/5.8.8/',
        # rhel6 32bit
        $pllib_dir.'/lib/perl5/',
	$pllib_dir.'/share/perl5/',
        # rhel6 64bit
        $pllib_dir.'/lib64/perl5/',
	$pllib_dir.'/share/perl5/',
  );

  push @INC, @incs;
};

use strict;
use warnings;
use utf8;
use Net::SNMP;
use Time::HiRes;
use Benchmark ':hireswallclock';
# use Smart::Comments;
use Data::Dumper;
use Locale::Messages qw (textdomain bindtextdomain gettext nl_putenv :locale_h :libintl_h);
use POSIX qw (setlocale);
binmode(STDIN, ":encoding(utf8)");
binmode(STDOUT, ":encoding(utf8)");
binmode(STDERR, ":encoding(utf8)");
binmode STDOUT, ':raw';

$| = 1;

# return codes
our ($state_succ,$state_warn,$state_crit,$state_unkn,$state_noop,$state_notify) = (0,1,2,3,4,5);

# return stuff
our ($rc, $result) = (0,'');

our $filename = (split /\//, __FILE__)[-1];

# check mole
unless (-f $mole && -x $mole) {
  printf "{unkn}:{str}:{$mole not prepared.}";
  exit $state_unkn;
}

# read mole locale_def
our $localdir = "$basedir/share/locale/";
open my $fh, "$mole printdef LOCALE_DIR 2>&- |";
if($fh){
  while(<$fh>){
        chomp; $localdir = $_;
        last;
  }
}

# read plugin locale setting
our $locale = 'zh_CN.UTF-8';
open $fh, "$mole view $filename locale 2>&- |";
if($fh){
  while(<$fh>){
        chomp; $locale = $_;
        last;
  }
  if(!defined $locale || $locale eq ''){
        open my $fh1, "$mole view default locale 2>&- |";
        if($fh1){
                while(<$fh1>){
                        chomp; $locale = $_;
                        last;
                }
        }
  }
}
if(!defined $locale || $locale eq ''){
        $locale = 'zh_CN.UTF-8';
}elsif($locale eq 'zh_CN' || $locale eq 'zh_CN.UTF-8' || $locale eq 'zh'){
        $locale = 'zh_CN.UTF-8';
}elsif($locale eq 'en_US' || $locale eq 'en_US.UTF-8' || $locale eq 'en'){
        $locale = 'en_US.UTF-8';
}else{
        $locale = 'zh_CN.UTF-8';
}
setlocale(LC_ALL,$locale);
nl_putenv("LANGUAGE=$locale");
nl_putenv("LANG=$locale");

# set textdomain; bindtextdomain
sub _ ($) { &gettext; }
textdomain "$filename";
bindtextdomain "$filename", "$localdir";

# read plugin config here
our $addr_port = undef;
open $fh, "$mole view $filename addr_port 2>&- |";
if ($fh) {
  while(<$fh>){
  	chomp; $addr_port = $_;
	last;
  }
}
if (!defined $addr_port) {
  printf _"{unkn}:{str}:{ addr_port not defined.}";
  exit $state_unkn;
}

our $time_out = undef;
open $fh, "$mole view $filename time_out 2>&- |";
if ($fh) {
  while(<$fh>){
  	chomp; $time_out = $_;
	last;
  }
}
if (!defined $time_out) {
  printf _"{unkn}:{str}:{ time_out shoule be defined as int.}";
  exit $state_unkn;
} elsif ($time_out =~ m/\D/) {
  printf _"{unkn}:{str}:{ time_out [%s] shoule be int.}",$time_out;
  exit $state_unkn;
}

our $comt_name = undef;
open $fh, "$mole view $filename comt_name 2>&- |";
if ($fh) {
  while(<$fh>){
  	chomp; $comt_name = $_;
	last;
  }
}
if (!defined $comt_name) {
  printf _"{unkn}:{str}:{ comt_name not defined.}";
  exit $state_unkn;
}


# Main body begin

my ($total,$critnum,$unknnum) = (0,0,0);
my ($time_start,$time_stop,$time_duration);

my %OID_DevInfo=(
	'SysName'	=>	'.1.3.6.1.2.1.1.5.0',
	'SysDescr'	=> 	'.1.3.6.1.2.1.1.1.0',
	'SysUptime'	=> 	'.1.3.6.1.2.1.1.3.0',
	'SystemDate'	=>	'.1.3.6.1.2.1.25.1.2.0',
	'Model'		=> 	'.1.3.6.1.2.1.25.3.2.1.3.1',
	'Serial'	=> 	'.1.3.6.1.2.1.43.5.1.1.17',
);
my %OID_Consumables=(
	'prConsumTable'	=> 	'.1.3.6.1.2.1.43.11.1.1',
	'prConsumNames'	=> 	'.1.3.6.1.2.1.43.11.1.1.6.1',
	'prConsumCapt'	=>	'.1.3.6.1.2.1.43.11.1.1.8.1',
	'prConsumRemi'	=>	'.1.3.6.1.2.1.43.11.1.1.9.1',
);
my %OID_Tray=(
	'prTrayTable'	=> 	'.1.3.6.1.2.1.43.8.2.1',
	'prTrayName'	=>	'.1.3.6.1.2.1.43.8.2.1.13.1',
	'prTrayCapt'	=> 	'.1.3.6.1.2.1.43.8.2.1.9.1',
	'prTrayRemi'	=>	'.1.3.6.1.2.1.43.8.2.1.10.1',
);
my $OID_PageCount = '.1.3.6.1.2.1.43.10.2.1.4.1.1';

$result = sprintf(_"check list: %s ### ### ",$addr_port);

my @addr_pair = split /\s+/, $addr_port;
while(@addr_pair) {
  $total++;
  my ($snmp_host, $snmp_port) = (split /:/, shift @addr_pair)[0,1];
  if (!defined $snmp_host || !defined $snmp_port) {
	$result .= sprintf(_"<font color=yellow> printer(snmp)_host or printer(snmp)_port not defined </font> ### ### ");
	$unknnum++;
	next;
  }
  if ($snmp_port =~ /\D/) {
	$result .= sprintf(_"<font color=yellow> %s:%s snmp port not numberic </font> ### ### ",$snmp_host,$snmp_port);
	$unknnum++;
	next;
  }

  $time_start = Benchmark->new();
  my ($snmp,$error) = Net::SNMP->session(
	-hostname     =>  $snmp_host,
	-port	      =>  $snmp_port,
	-timeout      =>  $time_out,
	-community    =>  $comt_name,
	-version      =>  'snmpv1',
	-nonblocking  =>  0,
	-retries      =>  3,
  );
  if (!defined $snmp) {
	$error =~ s/[\r\n]//g;
	$result .= sprintf(_"<font color=red> create snmp object on [%s:%d] return [%s] ",$snmp_host,$snmp_port,$error);
	$critnum++;
	goto ERREND;
  }

  
  next;

  ERREND: {
	if ($snmp) { $snmp->close(); }; 
	$time_stop = Benchmark->new();
	$time_duration = timestr(timediff($time_stop,$time_start),'noc');
	$time_duration = (split /\s+/, $time_duration )[0];
	$result .= sprintf(_" (%f seconds) </font> ### ### ",$time_duration);
	next;
  }
}

# prepare last output
if ($critnum > 0) {
  printf _"{crit}:{str}:{ Printer Check CRITICAL | %d/%d printer check critical | %s }",$critnum,$total,$result;
  exit $state_crit;
} elsif ($unknnum > 0) {
  printf _"{unkn}:{str}:{ Printer Check UNKNOWN | %d/%d printer check unknown | %s }",$unknnum,$total,$result;
  exit $state_unkn;
} else {
  printf _"{succ}:{str}:{ Printer Check OK | %d/%d printer check success | %s }",$total,$total,$result;
  exit $state_succ;
}
