#!/usr/bin/env perl

our $basedir = '/usr/local/esop/agent/mole';
our $mole = "$basedir/sbin/mole";

BEGIN {
  my $basedir = '/usr/local/esop/agent/mole';
  my $pllib_dir = "$basedir/opt/plmods";
  my @incs = (    # set additional path
        # rhel5 32bit
        $pllib_dir.'/lib/perl5/',
        $pllib_dir.'/lib/perl5/5.8.8/',
        $pllib_dir.'/lib/perl5/site_perl/',
        $pllib_dir.'/lib/perl5/site_perl/5.8.8/',
        # rhel5 64bit
        $pllib_dir.'/lib64/perl5/',
        $pllib_dir.'/lib64/perl5/5.8.8/',
        $pllib_dir.'/lib64/perl5/site_perl/',
        $pllib_dir.'/lib64/perl5/site_perl/5.8.8/',
        # rhel6 32bit
        $pllib_dir.'/lib/perl5/',
	$pllib_dir.'/share/perl5/',
        # rhel6 64bit
        $pllib_dir.'/lib64/perl5/',
	$pllib_dir.'/share/perl5/',
  );

  push @INC, @incs;
};

use strict;
use warnings;
use utf8;
use Encode;
use IO::Socket;
use IO::Socket::INET;
use Time::HiRes;
use Benchmark ':hireswallclock';
# use Smart::Comments;
use Locale::Messages qw (textdomain bindtextdomain gettext nl_putenv :locale_h :libintl_h);
use POSIX qw (setlocale);
binmode(STDIN, ":encoding(utf8)");
binmode(STDOUT, ":encoding(utf8)");
binmode(STDERR, ":encoding(utf8)");
binmode STDOUT, ':raw';

$| = 1;

# return codes
our ($state_succ,$state_warn,$state_crit,$state_unkn,$state_noop,$state_notify) = (0,1,2,3,4,5);

# return stuff
our ($rc, $result) = (0,'');

our $filename = (split /\//, __FILE__)[-1];

# check mole
unless (-f $mole && -x $mole) {
  printf "{unkn}:{str}:{$mole not prepared.}";
  exit $state_unkn;
}

# read mole locale_def
our $localdir = "$basedir/share/locale/";
open my $fh, "$mole printdef LOCALE_DIR 2>&- |";
if($fh){
  while(<$fh>){
        chomp; $localdir = $_;
        last;
  }
}

# read plugin locale setting
our $locale = 'zh_CN.UTF-8';
open $fh, "$mole view $filename locale 2>&- |";
if($fh){
  while(<$fh>){
        chomp; $locale = $_;
        last;
  }
  if(!defined $locale || $locale eq ''){
        open my $fh1, "$mole view default locale 2>&- |";
        if($fh1){
                while(<$fh1>){
                        chomp; $locale = $_;
                        last;
                }
        }
  }
}
if(!defined $locale || $locale eq ''){
        $locale = 'zh_CN.UTF-8';
}elsif($locale eq 'zh_CN' || $locale eq 'zh_CN.UTF-8' || $locale eq 'zh'){
        $locale = 'zh_CN.UTF-8';
}elsif($locale eq 'en_US' || $locale eq 'en_US.UTF-8' || $locale eq 'en'){
        $locale = 'en_US.UTF-8';
}else{
        $locale = 'zh_CN.UTF-8';
}
setlocale(LC_ALL,$locale);
nl_putenv("LANGUAGE=$locale");
nl_putenv("LANG=$locale");

# set textdomain; bindtextdomain
sub _ ($) { &gettext; }
textdomain "$filename";
bindtextdomain "$filename", "$localdir";

# read plugin config here
our $addr_port = '127.0.0.1:6379';
open $fh, "$mole view $filename addr_port 2>&- |";
if ($fh) {
  while(<$fh>){
  	chomp; $addr_port = $_;
	last;
  }
}

our $list_length = '';
open $fh, "$mole view $filename list_length 2>&- |";
if ($fh) {
  while(<$fh>){
  	chomp; $list_length = $_;
	last;
  }
}
if (!defined $list_length || $list_length eq '') {
  printf _"{unkn}:{str}:{ list_length not defined.}";
  exit $state_unkn;
}

our $time_out = undef;
open $fh, "$mole view $filename time_out 2>&- |";
if ($fh) {
  while(<$fh>){
  	chomp; $time_out = $_;
	last;
  }
}
if (!defined $time_out) {
  printf _"{unkn}:{str}:{ time_out shoule be defined as int.}";
  exit $state_unkn;
} elsif ($time_out =~ m/\D/) {
  printf _"{unkn}:{str}:{ time_out [%s] shoule be int.}",$time_out;
  exit $state_unkn;
}


# Main body begin
my ($total,$critnum,$unknnum) = (0,0,0);
my ($time_start,$time_stop,$time_duration);

$result = sprintf(_"check list: %s ### ### ",$addr_port);

my @addr_pair = split /\s+/, $addr_port;
while(@addr_pair) {
  $total++;
  my ($redis_host, $redis_port) = (split /:/, shift @addr_pair)[0,1];
  if (!defined $redis_host || !defined $redis_port) {
	$result .= sprintf(_"<font color=yellow> redis_host or redis_port not defined </font> ### ### ");
	$unknnum++;
	next;
  }
  if ($redis_port =~ /\D/) {
	$result .= sprintf(_"<font color=yellow> %s:%s redis port not numberic </font> ### ### ",$redis_host,$redis_port);
	$unknnum++;
	next;
  }

  my @addr_pair = split /\s+/, $addr_port;
  my ($list_name, $length_limit) = (split /:/, shift @list_length)[0,1];

  $time_start = Benchmark->new();
  my $redis=IO::Socket::INET->new(
	PeerAddr =>	$redis_host,
	PeerPort => 	$redis_port,
	Proto	 =>	'tcp',
	Timeout =>	($time_out =~ /\D/)?10:$time_out,
  );
  unless (defined $redis) {
	if ($@) {
		$@ =~ s/[\r\n]//g;
		$result .= sprintf(_"<font color=red> connect [%s:%d] failed in %d seconds, return [%s] ",$redis_host,$redis_port,$time_out,$@);
	} else {
		$result .= sprintf(_"<font color=red> connect [%s:%d] failed in %d seconds. ",$redis_host,$redis_port,$time_out);
	}
	$critnum++;
	goto ERREND;
  }

  print $redis "LLEN ma.json\r\n";
  my $response = <$redis>;
  unless (defined $response && $response =~ m/\A:(\d+)/i) {
        $response = '' if (!defined $response);
        $result .= sprintf(_"<font color=red> redis command: LLEN %s return [message=%s] ",$response);
        $critnum++;
        goto ERREND;
  } else {
	my $nowerlen = $1;
        $time_stop = Benchmark->new();
        $time_duration = timestr(timediff($time_stop,$time_start),'noc');
        $time_duration = (split /\s+/, $time_duration )[0];
        $response = '' if (!defined $response);
        $result .= sprintf(_"redis command: LLEN %s return [message=%s] (%f seconds) ### ",$response,$time_duration);
        $time_start = Benchmark->new();         ## reset time_start
  }

  next;

  ERREND: {
	if ($redis) { $redis->close(); }; 
	$time_stop = Benchmark->new();
	$time_duration = timestr(timediff($time_stop,$time_start),'noc');
	$time_duration = (split /\s+/, $time_duration )[0];
	$result .= sprintf(_" (%f seconds) </font> ### ### ",$time_duration);
	next;
  }
}
# prepare last output
if ($critnum > 0) {
  printf _"{crit}:{str}:{ REDIS LIST LENGTH CRITICAL | %d/%d redis list check critical | %s }",$critnum,$total,$result;
  exit $state_crit;
} elsif ($unknnum > 0) {
  printf _"{unkn}:{str}:{ REDIS LIST LENGTH UNKNOWN | %d/%d redis list check unknown | %s }",$unknnum,$total,$result;
  exit $state_unkn;
} else {
  printf _"{succ}:{str}:{ REDIS LIST LENGTH OK | %d/%d redis list check success | %s }",$total,$total,$result;
  exit $state_succ;
}
