#!/usr/bin/env bash

# BASE_DIR DEF
[ -z ${BASE_DIR} ] && { 
        path=$( cd $(dirname $0) && pwd)
        BASE_DIR=${path%/*}
}

# === LOAD GETTEXT.SH FILE
if [ -f "/usr/bin/gettext.sh"  -a -s "/usr/bin/gettext.sh" ]; then
        source "/usr/bin/gettext.sh" 2>&1
        rc=$?
        [ "$rc" != "0" ] && {
                echo -en "{unkn}:{str}:{load [/usr/bin/gettext.sh] failed with status $rc}"
                exit 3
        }
else
        echo -en "{unkn}:{str}:{[/usr/bin/gettext.sh] not exists or empty, maybe gettext not installed. exit}"
        exit 3
fi

# === LOAD INCLUDE FILE
if [ -f "${BASE_DIR}/bin/include" -a -s "${BASE_DIR}/bin/include" ]; then
        source ${BASE_DIR}/bin/include 2>&-
else
        echo -en "{unkn}:{str}:{include file not exists or empty}"
	exit 3
fi

# === SET TEXTDOMAINDIR TEXTDOMAIN
if [ -d "${LOCALE_DIR}" -a -r "${LOCALE_DIR}" ]; then
        export TEXTDOMAINDIR="${LOCALE_DIR}"
        export TEXTDOMAIN="cpu_usage"
else
        echo -en "{unkn}:{str}:{locale directory [${LOCALE_DIR}] not exist or accessable, exit}"
        exit 3
fi

# === SET GLOBAL LOCALE
glocale=$(get_locale cpu_usage)
if [ -z "${glocale}" ]; then
        export LANG="zh_CN.UTF-8"           ## read from sysenv
elif [ "${glocale}" == "zh_CN" -o "${glocale}" == "zh_CN.UTF-8" -o "${glocale}" == "zh" ]; then
        export LANG="zh_CN.UTF-8"
elif [ "${glocale}" == "en_US" -o "${glocale}" == "en_US.UTF-8" -o "${glocale}" == "en" ]; then
        export LANG="en_US.UTF-8"
else
	export LANG="zh_CN.UTF-8"
fi


show_help(){
cat <<EOF
Arguments:   {d|data|h|help}

Usage	 :   data

Output   :   usa_pct% wait_pct% sys_pct% usr_pct%
Example  :   0.4 0.2 0 0
EOF
exit 0;
}
MODE=0
[ "$1" == "data" -o "$1" == "d" ] && MODE=1
[ "$1" == "help" -o "$1" == "h" ] && show_help;


# Return Codes
STATE_SUCC=0
STATE_WARN=1
STATE_CRIT=2
STATE_UNKN=3
STATE_NOOP=4
STATE_NOTIFY=5

# Set Default
EXIT_STATUS=0
LEVEL=    	### { succ | warn | crit | unkn | noop | notify }
TYPE=    	### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
uplimit=$( read_mole_config cpu_usage uplimit )
wa_uplimit=$( read_mole_config cpu_usage wa_uplimit )
sy_uplimit=$( read_mole_config cpu_usage sy_uplimit )
us_uplimit=$( read_mole_config cpu_usage us_uplimit )

# if null return STATE_UNKN.

# if null or invalid set default.
[ -z "${uplimit}" -o ! -z "${uplimit//[0-9]}" ] && uplimit=75
[ -z "${wa_uplimit}" -o ! -z "${wa_uplimit//[0-9]}" ] && wa_uplimit=20
[ -z "${sy_uplimit}" -o ! -z "${sy_uplimit//[0-9]}" ] && sy_uplimit=30
[ -z "${us_uplimit}" -o ! -z "${us_uplimit//[0-9]}" ] && us_uplimit=50

# check function here
check(){

  if [ ! -x "/usr/bin/vmstat" ]; then
	EXIT_STATUS=${STATE_UNKN};
	LEVEL="unkn";
	TYPE="str";
	CONTENT="$(gettext "Command: [/usr/bin/vmstat] not prepared.")";
	return
  fi

  # collect data
  local cpu_usage=
  cpu_usage=( $( /usr/bin/vmstat 1 5 | tail -n +3 |\
	awk '{id+=$15;wa+=$16;sy+=$14;us+=$13} END{print 100-id/5,wa/5,sy/5,us/5}' 2>&1 ) )

  # output data and exit if MODE=1
  [ "${MODE}" == "1" ] && {
	echo "${cpu_usage[*]}"
	exit;
  }

  p_usage="${cpu_usage[0]}";
  wa_usage="${cpu_usage[1]}"
  sy_usage="${cpu_usage[2]}";
  us_usage="${cpu_usage[3]}"

  oknum=0 warnnum=0 result=
  if [ "$(echo  "${p_usage} >= ${uplimit}" | bc 2>&-)" == "1" ]; then
	((warnnum++))
	result="${result} $(html_red "$(eval_gettext "cpu usage: [\${p_usage}%] >= uplimit: [\${uplimit}%]")") ###"
  else
	((oknum++))
	result="${result} $(eval_gettext "cpu usage: [\${p_usage}%] <= uplimit: [\${uplimit}%]") ###"
  fi

  if [ "$(echo  "${wa_usage} >= ${wa_uplimit}" | bc 2>&-)" == "1" ]; then
	((warnnum++))
	result="${result} $(html_red "$(eval_gettext "cpu wait usage: [\${wa_usage}%] >= uplimit: [\${wa_uplimit}%]")") ###"
  else
	((oknum++))
	result="${result} $(eval_gettext "cpu wait usage: [\${wa_usage}%] <= uplimit: [\${wa_uplimit}%]") ###"
  fi

  if [ "$(echo  "${sy_usage} >= ${sy_uplimit}" | bc 2>&-)" == "1" ]; then
	((warnnum++))
	result="${result} $(html_red "$(eval_gettext "cpu sys usage: [\${sy_usage}%] >= uplimit: [\${sy_uplimit}%]")") ###"
  else
	((oknum++))
	result="${result} $(eval_gettext "cpu sys usage: [\${sy_usage}%] <= uplimit: [\${sy_uplimit}%]") ###"
  fi

  if [ "$(echo  "${us_usage} >= ${uplimit}" | bc 2>&-)" == "1" ]; then
	((warnnum++))
	result="${result} $(html_red "$(eval_gettext "cpu user usage: [\${us_usage}%] >= uplimit: [\${us_uplimit}%]")") ###"
  else
	((oknum++))
	result="${result} $(eval_gettext "cpu user usage: [\${us_usage}%] <= uplimit: [\${us_uplimit}%]") ###"
  fi

  total=$((${warnnum}+${oknum}))
  if [ ${warnnum} -gt 0 ]; then
	local top_pcpu_ps=$(ps -eo pid,comm,pcpu|tail -n +2|sort -rn -k 3|head|sed -e 's/$/###/g' | tr -d '\n')
	EXIT_STATUS=${STATE_WARN};
	LEVEL="warn";
	TYPE="str";
	CONTENT="$(gettext "CPU Usage Check WARNING") | $(eval_gettext "\${warnnum}/\${total} check failed.") | ${result} ### ### $(gettext "cpu usage top10:") ### ${top_pcpu_ps}"
  else
	EXIT_STATUS=${STATE_SUCC};
	LEVEL="succ";
	TYPE="str";
	CONTENT="$(gettext "CPU Usage Check OK") | $(eval_gettext "\${oknum}/\${total} check success.") | ${result}"
  fi
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
